services:
  
  rag:
    image: python:3.9   # Docker Swarm requires to specify the image used even if it is already specified in the Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile.rag
    # depends_on:
    #   - chroma
    #   - ollama
    ports:
      - 8080:80   # port 8080 of the host is mapped to port 80 of the container
    networks:
      - rag-frontend-net
      - rag-backend-net
    command: tail -F anything
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname == frontend-chroma-vm

networks:
  rag-frontend-net:
    name: rag-frontend-net
    external: true
  rag-backend-net:
    name: rag-backend-net
    external: true
